<?xml version="1.0"?>

<robot name="basic_geometry_pig" 
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Standard Params -->
    <xacro:property name="pi" value="3.1415" />

    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </xacro:macro>

    <!-- Basic Geometry of Body -->
    <xacro:property name="width" value="0.680618" />
    <xacro:property name="height" value="1.065022" />
    <xacro:property name="length" value="1.91" />

    <!-- The Ackerman Steering Hub -->
    <xacro:property name="ackerman_joint_diameter" value="0.09" />
    <xacro:property name="ackerman_joint_width" value="0.09" />

    <!-- Front Wheel Properties -->
    <xacro:property name="front_wheel_width" value=".254" />
    <xacro:property name="front_wheel_diameter" value="0.605" />

    <!-- Rear Wheel Properties -->
    <xacro:property name="rear_wheel_width" value="0.2794" />
    <xacro:property name="rear_wheel_diameter" value="0.635" />

    <!-- Main Body of Little Pig -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${length} ${width} ${height}"/>
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${length} ${width} ${height}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="49.8952"/>
            <inertia ixx="11.48" ixy="10.52" ixz="1.737" iyy="1.737" iyz="11.48" izz="10.52"/>
        </inertial>
    </link>

    <!-- Ackerman Steering Macro -->
    <xacro:macro name="ackerman_steering" params="prefix reflect">

        <!-- The Link -->
        <link name="${prefix}_ackerman_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${ackerman_joint_diameter/2}" length="${ackerman_joint_width}"/>
                </geometry>
                <material name="black" />
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${ackerman_joint_diameter/2}" length="${ackerman_joint_width}"/>
                </geometry>
            </collision>
            <xacro:default_inertial mass="2"/>
        </link>

        <!-- The Joint -->
        <joint name="${prefix}_ackerman_link_joint" type="revolute">
            <axis xyz="0.0 0.0 1.0" rpy="0.0 0.0 0.0"/>
            <parent link="base_link"/>
            <child link="${prefix}_ackerman_link"/>
            <origin xyz="${length / 2.5} ${((ackerman_joint_width/2) + (width/2)) * reflect} -${(height / 2.25) + (ackerman_joint_diameter / 2)}" rpy="0.0 0.0 0.0"/>
            <limit lower="-0.5" upper="0.5" effort="0.0" velocity="0.0"/>
        </joint>
    </xacro:macro>

    <!-- Front Wheel Macro -->
    <xacro:macro name="front_wheel" params="suffix reflect">

        <!-- The Link -->
        <link name="front_${suffix}_wheel">
            <visual>
                <origin xyz="0.0 ${(front_wheel_width/2) * reflect} 0.0" rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${front_wheel_diameter/2}" length="${front_wheel_width}"/>
                </geometry>
                <material name="black" />
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${front_wheel_diameter/2}" length="${front_wheel_width}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="20.995"/>
                <inertia ixx="0.996" ixy="0.0" ixz="0.0" iyy="0.612" iyz="0.0" izz="0.612"/>
            </inertial>
        </link>

        <!-- The Joint -->
        <joint name="ackerman_steering_to_front_${suffix}_wheel" type="continuous">
            <axis xyz="0.0 0.1 0.0"/>
            <parent link="${suffix}_ackerman_link"/>
            <child link="front_${suffix}_wheel"/>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </joint>

        <!-- Gazebo Interface -->
        <gazebo reference="front_${suffix}_wheel">
            <mu1 value="200.0"/>
            <mu2 value="100.0"/>
            <kp value="10000000.0" />
            <kd value="1.0" />
            <material>Gazebo/Black</material>
        </gazebo>

        <!-- The Transmission -->
        <transmission name="front_${suffix}_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="ackerman_steering_to_front_${suffix}_wheel">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="front_${suffix}_wheel_motor">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

    <!-- Back Wheel Macro -->
    <xacro:macro name="rear_wheel" params="suffix reflect">

        <!-- The Link -->
        <link name="rear_${suffix}_wheel">
            <visual>
                <origin xyz="0.0 ${(rear_wheel_width / 2) * reflect} 0.0" rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${rear_wheel_diameter/2}" length="${rear_wheel_width}"/>
                </geometry>
                <material name="black" />
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${rear_wheel_diameter/2}" length="${rear_wheel_width}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="20.995"/>
                <inertia ixx="0.996" ixy="0.0" ixz="0.0" iyy="0.612" iyz="0.0" izz="0.612"/>
            </inertial>
        </link>

        <!-- The Joint -->
        <joint name="base_to_rear_${suffix}_wheel" type="continuous">
            <axis xyz="0.0 1.0 0.0"/>
            <parent link="base_link"/>
            <child link="rear_${suffix}_wheel"/>
            <origin xyz="-${length / 2.5} ${(width /2) * reflect} -${(height / 5) + (rear_wheel_diameter / 2)}" rpy="0.0 0.0 0.0"/>
        </joint>

    </xacro:macro>

    <!-- Call the ackermans in for left/right -->
    <xacro:ackerman_steering prefix="left" reflect="1" />
    <xacro:ackerman_steering prefix="right" reflect="-1" />

    <!-- Call the front wheels in left/right -->
    <xacro:front_wheel suffix="left" reflect="1" />
    <xacro:front_wheel suffix="right" reflect="-1" />

    <!-- Call the rear wheels in left/right-->
    <xacro:rear_wheel suffix="left" reflect="1" />
    <xacro:rear_wheel suffix="right" reflect="-1" />

    <!-- Gazebo plugin for ROS Control -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/basic_geometry_pig</robotNamespace>
        </plugin>
    </gazebo>
</robot>